[config]
skip_core_tasks = true

[tasks.build]
category = "Tools"
description = "Build archive that Google want"
dependencies = ['bundle']
script = [
  'deno run --allow-read --allow-run scripts/build.ts',
]

[tasks.bundle]
category = "Tools"
description = "TypeScript to JavaScript"
script = [
  'deno run -A scripts/bundle.ts --entrypoint="../src/main.ts" > dist/main.js',
  'deno run -A scripts/bundle.ts --entrypoint="../src/options.tsx" > dist/options.js'
]

[tasks.resize]
category = "Tools"
description = "Resize icons that Google want"
script = [
  'mogrify -resize 128x128! assets/icon-*.png',
]

[tasks.help]
category = "Tools"
description = 'Might help you - (This one)'
script = [
  'makers --list-category-steps Tools',
]

