#!/usr/bin/env -S deno run --allow-read --allow-write

// Generate TypeScript constants from CSS files
const hideCssContent = Deno.readTextFileSync('src/github-patcher.css');
const showCssContent = Deno.readTextFileSync('src/github-patcher-show.css');

// Create the TypeScript content with the CSS as string constants
const tsContent = `// This file is auto-generated by generate-css-constants.ts
// Do not edit manually

export const HIDE_CSS_CONTENT = \`${hideCssContent}\`;

export const SHOW_CSS_CONTENT = \`${showCssContent}\`;
`;

// Write the generated TypeScript file
Deno.writeTextFileSync('src/css-constants.ts', tsContent);

console.log('Generated src/css-constants.ts from src/github-patcher.css and src/github-patcher-show.css');