name: CI - Nix
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-nix.yml'
      - '*.nix'
      - 'deno.jsonc'
  pull_request:
    paths:
      - '.github/workflows/ci-nix.yml'
      - '*.nix'
      - 'deno.jsonc'
  schedule:
    # About JST 8:00
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  tasks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix-shell --run 'deno task all'
