# https://github.com/NixOS/nixos-artwork/blob/35ebbbf01c3119005ed180726c388a01d4d1100c/logo/README.md#L5
name: ❄️
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-nix.yml'
      - '*.nix'
      - 'flake.*'
      - 'deno.jsonc'
      - '**.css'
  pull_request:
    paths:
      - '.github/workflows/ci-nix.yml'
      - '*.nix'
      - 'flake.*'
      - 'deno.jsonc'
      - '**.css'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

jobs:
  tasks:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - run: nix flake check
      - run: nix develop --command echo 'This step should be done before any other "nix develop" steps because of measuring Nix build time'
      - run: nix develop --command deno task all
