name: 🤖👌🤖
on: pull_request

permissions:
  contents: write
  pull-requests: write
  # checks: read # For private repositories
  # actions: read # For private repositories

jobs:
  judge-dependabot:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    outputs:
      merge: ${{ steps.conclusion.outputs.merge }}
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot
        uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34 # v2.2.0
      - name: Judge
        id: conclusion
        if: >-
          steps.dependabot.outputs.update-type != 'version-update:semver-major' ||
          contains(steps.dependabot.outputs.dependency-names, 'DeterminateSystems')
        run: echo -n 'merge=true' | tee -a "$GITHUB_OUTPUT"
  dependabot:
    runs-on: ubuntu-24.04
    needs: [judge-dependabot]
    if: ${{ needs.judge-dependabot.outputs.merge == 'true' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0
      - name: Wait other jobs
        uses: kachick/wait-other-jobs@v3
        with:
          skip-same-workflow: 'true'
          skip-list: |
            [
              {
                "workflowFile": "release.yml"
              }
            ]
        timeout-minutes: 10
      - name: Approve and merge
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  # https://github.com/kachick/anylang-template/issues/51
  selfup-runner:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    if: ${{ github.actor == 'selfup-runner[bot]' }}
    steps:
      - name: Wait other jobs
        uses: kachick/wait-other-jobs@v3
        with:
          skip-same-workflow: 'true'
          skip-list: |
            [
              {
                "workflowFile": "release.yml"
              }
            ]
        timeout-minutes: 20
      - name: Approve and merge
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --delete-branch --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
