name: 🚀
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    # https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128
    permissions:
      contents: write
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: '1.45.5' # selfup {"extract":"\\d[^']+","replacer":["bash","-c","deno --version | head -n 1 | cut -d ' ' -f 2"]}
      - name: Ensure cache before build
        run: deno task cache
      - name: Install gh-action-escape
        run: curl -fsSL https://raw.githubusercontent.com/kachick/gh-action-escape/v0.2.0/scripts/install-in-github-action.sh | sh -s v0.2.0
      - name: Build
        id: build
        run: deno task build | gh-action-escape -name=report | tee --append "$GITHUB_OUTPUT"
      - name: Wait other jobs
        uses: kachick/wait-other-jobs@v3
        with:
          skip-same-workflow: 'true'
          skip-list: |
            [
              {
                "workflowFile": "merge-bot-pr.yml"
              }
            ]
        if: startsWith(github.ref, 'refs/tags/')
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '${{ fromJson(steps.build.outputs.report).productPath }}'
