name: Release
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: '1.34.2'
      - name: Build
        id: build
        run: |
          report="$(deno task build)"
          echo "report=${report}" | tee -a "$GITHUB_OUTPUT"
      - name: Wait other jobs
        uses: kachick/wait-other-jobs@v1
        if: startsWith(github.ref, 'refs/tags/')
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '${{ fromJson(steps.build.outputs.report).productPath }}'
