name: 🚀
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    # https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128
    permissions:
      contents: write
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: denoland/setup-deno@v2
        with:
          deno-version: '2.5.6' # selfup {"extract":"\\d[^']+","replacer":["bash","-c","deno --version | head -n 1 | cut -d ' ' -f 2"]}
      - name: Ensure cache before build
        run: deno task cache
      - name: Build
        id: build
        run: |
          {
            echo 'report<<JSON'
            deno task build
            echo 'JSON'
          } 2>/dev/null | tee --append "$GITHUB_OUTPUT"
      - name: Wait other jobs
        uses: kachick/wait-other-jobs@v3
        with:
          skip-same-workflow: 'true'
          skip-list: |
            [
              {
                "workflowFile": "merge-bot-pr.yml"
              }
            ]
        if: startsWith(github.ref, 'refs/tags/')
      - name: Release
        # TODO: Replace with gh command
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '${{ fromJson(steps.build.outputs.report).productPath }}'
