name: Release
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    # https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128
    permissions:
      contents: write
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: '1.34.2'
      - name: Ensure cache before build
        run: deno task cache
      - name: Install gh-action-multiline
        run: curl -fsSL https://raw.githubusercontent.com/kachick/gh-action-multiline/v0.1.0/scripts/install-in-github-action.sh | sh -s
      - name: Build
        id: build
        run: deno task build | gh-action-multiline report | tee --append "$GITHUB_OUTPUT"
      - name: Wait other jobs
        uses: kachick/wait-other-jobs@v1
        with:
          min-interval-seconds: '15'
        if: startsWith(github.ref, 'refs/tags/')
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '${{ fromJson(steps.build.outputs.report).productPath }}'
