name: Stylelint
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/stylelint.yml'
      - '**.css'
      - 'deno.*'
  pull_request:
    paths:
      - '.github/workflows/stylelint.yml'
      - '**.css'
      - 'deno.*'

jobs:
  check:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: '1.36.0' # selfup { "regex": "\\d[^']+", "script": "deno --version | head -n 1 | cut -d ' ' -f 2" }
      - run: deno task stylelint
