name: 🤖🆙❄️
on:
  pull_request:
    paths:
      - '.github/workflows/update-flake-lock-and-ci.yml'
  schedule:
    # Every Monday 10:17 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '17 1 * * 1'
  workflow_dispatch:

jobs:
  update-nixpkgs:
    uses: kachick/selfup/.github/workflows/reusable-bump-flake-lock-and-selfup.yml@v1.3.1
    with:
      app_id: ${{ vars.APP_ID }}
      dry-run: ${{ github.event_name == 'pull_request' }}
      pr-title: 'Bump flake.lock and related dependencies'
      # Do not scope `git commit` to specific files.
      # Other files like icons (via `mogrify`) or formatted codes (via `dprint`) may be updated during these tasks.
      # Scoped commit will fail if the target file itself is not modified but others are.
      optional-run: |
        nix develop --command deno task 'bump:biome_config'
        git update-index --refresh || true
        git diff-index --quiet HEAD || git commit -m 'Bump biome.json and related changes' .
        nix develop --command deno task 'bump:deno_lock'
        git update-index --refresh || true
        git diff-index --quiet HEAD || git commit -m 'Bump deno.lock and related changes' .
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
